In [1]:
import pandas as pd
df_raw = pd.read_csv("marketing_campaign_data_messy.csv")
df1 = df_raw.copy()

In [2]:
#STEP 1 : cleaning the headers
df1.columns = df1.columns.str.strip().str.lower().str.replace(" ", "_")
df1.columns

Index(['campaign_id', 'campaign_name', 'start_date', 'end_date', 'channel',
       'impressions', 'clicks', 'spend', 'conversions', 'active', 'clicks',
       'campaign_tag'],
      dtype='object')

In [3]:
#STEP 2 : Cleaning of the column "spend" by removing the "$"
df1["spend"] = df1["spend"].str.replace("$", "", regex = False)
df1["spend"] = df1["spend"].astype(float)
df1["spend"].head(10)
#If there are some values like "N/A", "unknown" in the column : 
#df["spend"] = df["spend"].str.replace("$", "", regex=False)
#df["spend"] = pd.to_numeric(df["spend"], errors="coerce") errors = "coerce" transforms unvalid values in NaN

0     102.82
1      24.33
2    1323.39
3    2180.38
4     252.44
5    2697.03
6    1232.76
7     865.70
8    1046.18
9    1623.56
Name: spend, dtype: float64

In [4]:
#STEP 3 : standardizing the names of the channels
df1["channel"] = df1["channel"].str.lower().str.strip().str.replace(r"[_-]", "", regex = True)
df1["channel"] = df1["channel"].replace({"gogle" : "google ads", "facebok" : "facebook"})
df1

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,clicks,campaign_tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24 00:00:00,2023-12-13,tiktok,16795,197,102.82,20.0,Y,NaN,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06 00:00:00,2023-05-12,facebook,1860,30,24.33,1.0,0,NaN,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13 00:00:00,2023-12-20,email,77820,843,1323.39,51.0,No,NaN,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,tiktok,55886,2019,2180.38,135.0,True,NaN,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22 00:00:00,2023-04-23,facebook,7265,169,252.44,30.0,Yes,NaN,FA
...,...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31 00:00:00,2023-11-13,tiktok,30592,586,503.95,77.0,1,NaN,TI
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01 00:00:00,2023-09-26,google ads,20097,897,1641.00,162.0,0,NaN,GO
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09 00:00:00,2023-02-21,instagram,33254,1117,883.82,214.0,0,NaN,IN
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30 00:00:00,2023-04-27,facebook,68728,2960,4198.50,591.0,Yes,NaN,FA
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26 00:00:00,2023-07-09,email,96402,1090,1315.59,66.0,Y,NaN,EM

In [5]:
#STEP 4 : Standardizing the date format
df1["start_date_clean"] = pd.to_datetime(df1["start_date"], format = "mixed", dayfirst = True, errors = "coerce")
df1["end_date"] = pd.to_datetime(df1["end_date"], format = "mixed", dayfirst = True, errors = "coerce")
df1["start_date_clean"].isna().sum()

np.int64(0)

In [6]:
#STEP 5 : cleaning the campaign_tag
df1["campaign_tag"] = df1["channel"].map({"tiktok" : "TI",
                                         "facebook" : "FA",
                                         "email" : "EM",
                                         "instagram" : "IN",
                                         "google ads" : "GA"})
df1

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,clicks,campaign_tag,start_date_clean
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24 00:00:00,2023-12-13,tiktok,16795,197,102.82,20.0,Y,NaN,TI,2023-11-24
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06 00:00:00,2023-05-12,facebook,1860,30,24.33,1.0,0,NaN,FA,2023-05-06
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13 00:00:00,2023-12-20,email,77820,843,1323.39,51.0,No,NaN,EM,2023-12-13
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,tiktok,55886,2019,2180.38,135.0,True,NaN,TI,2023-10-30
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22 00:00:00,2023-04-23,facebook,7265,169,252.44,30.0,Yes,NaN,FA,2023-04-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31 00:00:00,2023-11-13,tiktok,30592,586,503.95,77.0,1,NaN,TI,2023-10-31
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01 00:00:00,2023-09-26,google ads,20097,897,1641.00,162.0,0,NaN,GA,2023-09-01
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09 00:00:00,2023-02-21,instagram,33254,1117,883.82,214.0,0,NaN,IN,2023-02-09
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30 00:00:00,2023-04-27,facebook,68728,2960,4198.50,591.0,Yes,NaN,FA,2023-03-30
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26 00:00:00,2023-07-09,email,96402,1090,1315.59,66.0,Y,NaN,EM,2023-06-26

In [7]:
df1["channel"].unique()

array(['tiktok', 'facebook', 'email', 'instagram', 'google ads', nan],
      dtype=object)

In [8]:
#STEP 6 : replacing start_date by start_date_clean and droping start_clean_date
df1["start_date"] = df1["start_date_clean"]
df1 = df1.drop(columns = ["start_date_clean"])

In [9]:
#STEP 7 : Removing empty column clicks
df1.columns.duplicated() #Show which column is a duplicate ex : [clicks, date, clicks, campaign_id] becomes [False, False, True, False]
df1 = df1.loc[:, ~df1.columns.duplicated(keep = "first")] #  df1.loc[:, df1.columns.duplicated()] this would select only the columns that are duplicates.  
                                            # By adding "~" we reverse it so we have only the columns with no duplicates. We keep only original columns

In [10]:
#STEP 8 : standardizing the expected output for the "active" column
df1["active"] = df1["active"].astype(str).str.lower().str.strip()
df1["active"] = df1["active"].map({
    "y" : True,
    "yes" : True,
    "1" : True,
    "true" : True,
    "no" : False,
    "n" : False,
    "0" : False,
    "false" : False})
df1

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,campaign_tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,tiktok,16795,197,102.82,20.0,True,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,facebook,1860,30,24.33,1.0,False,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,email,77820,843,1323.39,51.0,False,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,tiktok,55886,2019,2180.38,135.0,True,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,facebook,7265,169,252.44,30.0,True,FA
...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31,2023-11-13,tiktok,30592,586,503.95,77.0,True,TI
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01,2023-09-26,google ads,20097,897,1641.00,162.0,False,GA
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09,2023-02-21,instagram,33254,1117,883.82,214.0,False,IN
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30,2023-04-27,facebook,68728,2960,4198.50,591.0,True,FA
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26,2023-07-09,email,96402,1090,1315.59,66.0,True,EM

In [12]:
#STEP 9 : Deciding what to do with null values
df1["channel"] = df1["channel"].fillna("unknown")
df1["campaign_tag"] = df1["campaign_tag"].fillna("unknown")
df1

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,campaign_tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,tiktok,16795,197,102.82,20.0,True,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,facebook,1860,30,24.33,1.0,False,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,email,77820,843,1323.39,51.0,False,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,tiktok,55886,2019,2180.38,135.0,True,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,facebook,7265,169,252.44,30.0,True,FA
...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31,2023-11-13,tiktok,30592,586,503.95,77.0,True,TI
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01,2023-09-26,google ads,20097,897,1641.00,162.0,False,GA
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09,2023-02-21,instagram,33254,1117,883.82,214.0,False,IN
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30,2023-04-27,facebook,68728,2960,4198.50,591.0,True,FA
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26,2023-07-09,email,96402,1090,1315.59,66.0,True,EM

In [19]:
df1.to_csv("marketing_campaign_data_clean.csv", index=False, encoding="utf-8-sig")

In [20]:
df2 = pd.read_csv("marketing_campaign_data_clean.csv")
df2

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,campaign_tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,tiktok,16795,197,102.82,20.0,True,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,facebook,1860,30,24.33,1.0,False,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,email,77820,843,1323.39,51.0,False,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,tiktok,55886,2019,2180.38,135.0,True,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,facebook,7265,169,252.44,30.0,True,FA
...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31,2023-11-13,tiktok,30592,586,503.95,77.0,True,TI
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01,2023-09-26,google ads,20097,897,1641.00,162.0,False,GA
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09,2023-02-21,instagram,33254,1117,883.82,214.0,False,IN
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30,2023-04-27,facebook,68728,2960,4198.50,591.0,True,FA
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26,2023-07-09,email,96402,1090,1315.59,66.0,True,EM